In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/organizations/uciml/el-nino-dataset/elnino.csv

# Getting to know the dataset


## This dataset contains information about factors that lead to the El Nino Southern Oscillations.



### El Niño–Southern Oscillation (ENSO) is a global climate phenomenon that emerges from variation in winds and sea surface temperatures over the tropical Pacific Ocean. This dataset contains featuresused for El Nino prediction.

In [2]:
df_original = pd.read_csv('/kaggle/input/datasets/organizations/uciml/el-nino-dataset/elnino.csv')

In [3]:
df_original.head()

,Observation,Year,Month,Day,Date,Latitude,Longitude,Zonal Winds,Meridional Winds,Humidity,Air Temp,Sea Surface Temp
0,1,80,3,7,800307,-0.02,-109.46,-6.8,0.7,.,26.14,26.24
1,2,80,3,8,800308,-0.02,-109.46,-4.9,1.1,.,25.66,25.97
2,3,80,3,9,800309,-0.02,-109.46,-4.5,2.2,.,25.69,25.28
3,4,80,3,10,800310,-0.02,-109.46,-3.8,1.9,.,25.57,24.31
4,5,80,3,11,800311,-0.02,-109.46,-4.2,1.5,.,25.3,23.19

## Removed leading white spaces from the column name

In [4]:
df_original.columns = df_original.columns.str.strip()

In [5]:
df_original.columns

Index(['Observation', 'Year', 'Month', 'Day', 'Date', 'Latitude', 'Longitude',
       'Zonal Winds', 'Meridional Winds', 'Humidity', 'Air Temp',
       'Sea Surface Temp'],
      dtype='object')

In [6]:
df_original.head()

,Observation,Year,Month,Day,Date,Latitude,Longitude,Zonal Winds,Meridional Winds,Humidity,Air Temp,Sea Surface Temp
0,1,80,3,7,800307,-0.02,-109.46,-6.8,0.7,.,26.14,26.24
1,2,80,3,8,800308,-0.02,-109.46,-4.9,1.1,.,25.66,25.97
2,3,80,3,9,800309,-0.02,-109.46,-4.5,2.2,.,25.69,25.28
3,4,80,3,10,800310,-0.02,-109.46,-3.8,1.9,.,25.57,24.31
4,5,80,3,11,800311,-0.02,-109.46,-4.2,1.5,.,25.3,23.19

## This dataset contains values from 1980 to 1998. But only the last two digits of the years is mentioned in the data. So, I added 1900 to each datapoint in the year column.

In [7]:
df_original["Year"]

0         80
1         80
2         80
3         80
4         80
          ..
178075    98
178076    98
178077    98
178078    98
178079    98
Name: Year, Length: 178080, dtype: int64

In [8]:
df_original["Year"] = df_original["Year"]+1900

In [9]:
df_original["Year"]

0         1980
1         1980
2         1980
3         1980
4         1980
          ...
178075    1998
178076    1998
178077    1998
178078    1998
178079    1998
Name: Year, Length: 178080, dtype: int64

## Checking for null values

In [10]:
df_original.count()

Observation         178080
Year                178080
Month               178080
Day                 178080
Date                178080
Latitude            178080
Longitude           178080
Zonal Winds         178080
Meridional Winds    178080
Humidity            178080
Air Temp            178080
Sea Surface Temp    178080
dtype: int64

In [11]:
df_original.replace(".", np.nan, inplace=True)

In [12]:
df_original.count()

Observation         178080
Year                178080
Month               178080
Day                 178080
Date                178080
Latitude            178080
Longitude           178080
Zonal Winds         152917
Meridional Winds    152918
Humidity            112319
Air Temp            159843
Sea Surface Temp    161073
dtype: int64

## After manually examining the dataset, I found that the null values were represented by '.' and not by nan or 0. So, I replaced the '.' with nan.